version : '3.9'

services:
  flask:
    build: .
    container_name: flask-application
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    expose:
      - 5000

    command: [ "poetry", "run", "python", "app.py" ]

    networks:
      - mlops

  classification:
    build: .
    container_name: classification-mlops
    volumes:
      - ./:/app
    ports:
      - 5001:5001
    expose:
      - 5001

    command: [ "poetry", "run", "python", "classification.py" ]

  regression:
    build: .
    container_name: regression-mlops
    volumes:
      - ./:/app
    ports:
      - 5002:5002
    expose:
      - 5002

    command: [ "poetry", "run", "python", "regression.py" ]

networks:
  mlops:
    driver: bridge